#!/bin/sh
# Gradle wrapper bootstrap script. On a real project this is generated by
# `gradle wrapper`. Since we can't include the binary jar in git via API,
# run `gradle wrapper --gradle-version 8.2` once to generate the full wrapper.

DIR="$(cd "$(dirname "$0")" && pwd)"
APP_HOME="$DIR"

if [ ! -f "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" ]; then
    echo "gradle-wrapper.jar not found. Run: gradle wrapper --gradle-version 8.2"
    exit 1
fi

exec java -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" \
    org.gradle.wrapper.GradleWrapperMain "$@"
